# Generated by Django 3.1.2 on 2020-10-28 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(default='', max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='upload/images/')),
            ],
        ),
        migrations.CreateModel(
            name='TshirtProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('tshirtproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.tshirtproperty')),
            ],
            bases=('shop.tshirtproperty',),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('tshirtproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.tshirtproperty')),
            ],
            bases=('shop.tshirtproperty',),
        ),
        migrations.CreateModel(
            name='IdealFor',
            fields=[
                ('tshirtproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.tshirtproperty')),
            ],
            bases=('shop.tshirtproperty',),
        ),
        migrations.CreateModel(
            name='NeckType',
            fields=[
                ('tshirtproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.tshirtproperty')),
            ],
            bases=('shop.tshirtproperty',),
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('tshirtproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.tshirtproperty')),
            ],
            bases=('shop.tshirtproperty',),
        ),
        migrations.CreateModel(
            name='Sleeve',
            fields=[
                ('tshirtproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.tshirtproperty')),
            ],
            bases=('shop.tshirtproperty',),
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=5)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tshirt')),
            ],
        ),
        migrations.AddField(
            model_name='tshirt',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='ideal_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.idealfor'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='neck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.necktype'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='ocassion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.occasion'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='sleeve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sleeve'),
        ),
    ]
