# Generated by Django 3.1.2 on 2020-11-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderitem_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_request_id',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
