# Generated by Django 3.1.2 on 2020-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201101_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_request_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
